version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "build"

  deploy: &deploy-env
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo "deploy"
      - run: bash ./scripts/apply_${env}.sh

  deploy_stage:
    <<: *deploy-env
    environment:
      env: stage

workflows:
  version: 2

  stage_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: terraform-testing
      - deploy:
          filters:
            branches:
              only: terraform-testing
          requires:
            - build 